#!/data/data/com.termux/files/usr/bin/bash 

echo "For audio only press a" 
echo "For video press v"
echo "For saving to batch press s"  

command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f' read option 
if [ "$option" -eq "a" ] then 
echo "$command 140" > ~/.config/youtube-dl/config youtube-dl $1 
elif [ "$option" -eq "v" ] then 
echo "enter quality"
read h
echo "$command \"best[height<=$h]"" > ~/.config/youtube-dl/config youtube-dl $1 

elif [ "$option" -eq "3" ] then echo -e "$1/n" >> "/storage/sdcard0/Youtube/batch.txt"
fi
